// This file is auto-generated by CI after every migration.
// Run `npm run db:types` locally to regenerate.
// Do not edit manually.
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];
export interface Database { public: { Tables: Record<string, unknown>; Views: Record<string, unknown>; Functions: Record<string, unknown>; Enums: Record<string, unknown>; } }
